name: kimegoto_dev
description: キメごと。開発環境です。

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  cloud_functions: ^3.2.15
  firebase_in_app_messaging: ^0.6.0+14
  firebase_storage: ^10.2.16
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  paginate_firestore: ^1.0.3+1
  flutter_line_sdk: ^2.1.0
  go_router: ^3.0.6
  google_sign_in: ^5.3.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  logger: ^1.1.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  shared_preferences: ^2.0.15
  hooks_riverpod: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # アイコン設定
  # $ flutter pub pub run flutter_launcher_icons:main
  flutter_launcher_icons: any
  build_runner: 2.2.0
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  json_serializable: 6.3.1
  json_annotation: 4.6.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/kimegoto2.png
    - assets/images/kimegoto3.png
    - assets/images/kimegoto4.png
    - assets/images/kimegoto5.png
    - assets/images/kimegoto6.png
    - assets/images/kimegoto7.png
    - assets/images/kimegoto8.png
    - assets/images/kimegoto9.png
    - assets/images/kimegoto10.png
    - assets/images/kimegoto11.png
    - assets/images/kimegoto12.png
    - assets/images/kimegoto13.png
    - assets/images/kimegoto14.png
    - assets/images/kimegoto15.png
    - assets/images/icon-sample1.jpeg
    - assets/images/icon-sample2.jpeg
    - assets/icon/
    - assets/fonts/
  fonts:
    - family: YuseiMagic
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/kimegotoicon.png"
  image_path_android: "assets/icon/kimegotoicon.png"
  adaptive_icon_foreground: "assets/icon/kimegotoicon.png"
  adaptive_icon_background: "assets/icon/kimegotoicon.png"
