name: flutter_analyze
on:
  push:
    branches:
      - develop
      - release

  pull_request:
    branches:
      - develop
      - release

jobs:
  lint:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v1
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"
          channel: "stable"
          cache: true
          # optional, change this to force refresh cache
          cache-key: flutter_cache.1
      - name: flutter pub get
        run: flutter pub get
      - name: flutter analyze
        run: flutter analyze